"""initial_tables

Revision ID: 86454001e975
Revises: 
Create Date: 2026-03-19 00:25:59.288140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86454001e975'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False, comment='음료/식품/생활용품/담배/기타'),
    sa.Column('cost_price', sa.Float(), nullable=True, comment='입고가'),
    sa.Column('selling_price', sa.Float(), nullable=True, comment='판매가'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=True)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('store_name', sa.String(length=100), nullable=False, comment='점포명'),
    sa.Column('store_address', sa.String(length=500), nullable=True, comment='점포 주소'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('weather_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('avg_temp', sa.Float(), nullable=True, comment='평균 기온(°C)'),
    sa.Column('condition', sa.String(length=20), nullable=True, comment='sunny/cloudy/rainy/snowy'),
    sa.Column('precipitation', sa.Float(), nullable=True, comment='강수량(mm)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', name='uq_weather_date')
    )
    op.create_index(op.f('ix_weather_data_date'), 'weather_data', ['date'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False, comment='holiday/school/local/other'),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_date'), 'events', ['event_date'], unique=False)
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_table('promotions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False, comment='상품명'),
    sa.Column('promotion_name', sa.String(length=200), nullable=False, comment='행사명'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='행사 시작일'),
    sa.Column('end_date', sa.Date(), nullable=False, comment='행사 종료일'),
    sa.Column('cost_price', sa.Float(), nullable=False, comment='원가'),
    sa.Column('sale_price', sa.Float(), nullable=False, comment='판매가'),
    sa.Column('expected_qty', sa.Integer(), nullable=False, comment='예상 판매량'),
    sa.Column('waste_rate', sa.Float(), nullable=False, comment='폐기율 (%)'),
    sa.Column('joined', sa.Boolean(), nullable=False, comment='행사 참여 여부'),
    sa.Column('actual_qty', sa.Integer(), nullable=True, comment='실제 판매량'),
    sa.Column('actual_profit_rate', sa.Float(), nullable=True, comment='실제 이익율 (%)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotions_user_id'), 'promotions', ['user_id'], unique=False)
    op.create_table('sales_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('sale_time', sa.Time(), nullable=True, comment='판매 시간'),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False, comment='총 판매금액'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_records_product_id'), 'sales_records', ['product_id'], unique=False)
    op.create_index(op.f('ix_sales_records_sale_date'), 'sales_records', ['sale_date'], unique=False)
    op.create_index(op.f('ix_sales_records_user_id'), 'sales_records', ['user_id'], unique=False)
    op.create_table('upload_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False, comment='csv/excel/screenshot'),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='processing/completed/failed'),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_histories_user_id'), 'upload_histories', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_histories_user_id'), table_name='upload_histories')
    op.drop_table('upload_histories')
    op.drop_index(op.f('ix_sales_records_user_id'), table_name='sales_records')
    op.drop_index(op.f('ix_sales_records_sale_date'), table_name='sales_records')
    op.drop_index(op.f('ix_sales_records_product_id'), table_name='sales_records')
    op.drop_table('sales_records')
    op.drop_index(op.f('ix_promotions_user_id'), table_name='promotions')
    op.drop_table('promotions')
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_date'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_weather_data_date'), table_name='weather_data')
    op.drop_table('weather_data')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
